= Document

== What composes a document
A document is a composition of different types of data. In its very minimallistic form,
it would be a simple image. However, an image by itself is not usable in a document
storage solution. The document must be identified by a certain amount of information
to actually be usable. After years of working with different document storage systems,
Monument has been designed to require some meta-data.

== Filename
A lot of times a filename is not useful. But in other instance some file name 
naming conventions provide useful information for locating a document.

== Document Category
This is the highest level categorization of documents. It is text data that should
define the category of documents. This will be required by each document and must
be configured in the system. This is also one of the primary fields used for 
security constraints to accessing documents. Document retention policies can be
defined at this level.

== Document Type
Within each category individual document types can be defined. This is a required
text field and must be configured within the system. This field can also be used
for security constraints for accessing documents. Document retention policies can
be defined at this level and will override the category retention policy.

== Defined Fields
Each document type within a category can define the meta-data fields that can
exist and are required to define a document. Monument allows for data validation
to be defined on each field element.

== Comments
Often times, it is helpful for general text comments be associated with a document.
Monument allows for comments to be added to a document by users with appropriate
permissions. Comments can be added, searched, modified, and deleted with correct 
permissions.

== Searchable Text
All documents can have the text of the document added in the searchable text data
section. Monument can be setup to automatically add this data from different 
acceptable formats, such as scanning PDFs for text, OCR capturing of the data
from images, etc. This is configurable by category and type.

== Unique Identifiable Key (UIK)
This is a unique key assigned by the system that is returned when a document is added. This allows for other systems to integrate easily where only a single value needs to be stored identifying a document. Think of it as the primary key.

== Versions
Documents can be set up to be versioned. Keeping an entire audit history of any
changes that have happened to the document over time.

== Example Document Defined
*Version 2*

'''
*Filename:* my_fancy_img.png +
*Document Category:* Human Resources +
*Document Type:* Acceptance Letter +
*Employee Name:* David Thompson +
*Document Date:* Apr 1, 2012 +
*Comment 1 (Alice Cooper):* Hand delivered for scanning +
*Comment 2 (Ace Frehley):* David requested a copy of his letter be printed +
*Searchable Text:* --Redacted at the request of the employee--

*Version 1*

'''
*Filename:* my_fancy_img.png +
*Document Category:* Human Resources +
*Document Type:* Acceptance Letter +
*Employee Name:* David Thompsn +
*Document Date:* Apr 1, 2012 +
*Comment 1 (Alice Cooper):* Hand delivered for scanning +
*Comment 2 (Ace Frehley):* David requested a copy of his letter be printed +
*Searchable Text:* Dear David We are pleased to offer you the job as IT janitor and 
are offering you the substantial salary of $12000 per year
 