= Pyx (A completely encompassing document)

== Why Pyx
The standard definition of a pyx is a container to store consecrated host to the
sick. We needed a term was similar to image or document but fit more the theme
of storing a collection of relics. With the play on words, Pyx seems to fit the
bill fantastically.

== What composes a pyx
A pyx is a collection of relics, a relic is just a single data element, so in
essence a pyx is a collection of data elements. In its very minimalistic form,
a pyx could be a collection of one relic with the image's binary information
within it. However, the binary image information by itself is not practical.
To actually be usable, the document must contain information to help identify what
the image contains. There are small set of preconfigured relic types that are
included within each pyx.

=== Required Predefined Relics

Filename::
A lot of times a filename is not useful. But in other instance some file name
naming conventions provide useful information for locating a document.

Classification::
This is the highest level grouping of pyxes. It is textual data that should
define the category of a pyx. This will be required by each document and any
document without one will be assigned to "nonclassified". This is also one of
the primary relics used for defining security constraints. Retention policies
can be defined at this level.

Unique Identifiable Key (UIK)::
This is a unique key assigned by the system that is returned when a pyx is
added. This allows for other systems to integrate easily where only a single
value needs to be stored identifying a document. Think of it as the primary key.

Import Date::
The date/timestamp the document is originally added to monument.

=== Optional Predefined Relics
There are also a set of predefined relics that are optionally added to a pyx
based on system configuration.

EXIF Data::
The data stored within the EXIF headers of many image formats. This can contain
location and date information.

Security Checksum::
Data storing the stored image checksum for security purposes.

Text::
The textual representation of the document. Can be added via a document
recognition process.

Version::
Documents can be set up to be versioned. Keeping an entire audit history of any
changes that have happened to the document over time.

== User Defined Relics
Each pyx can define the relic fields that can exist and are required to
define itself. Monument allows for validation to be defined on each relic
value provided.

== The Nonclassified Pyx
Preconfigured by the system upon installation is a special classification with
the name "nonclassified". This Pyx allows for users with appropriate permissions
to bulk upload documents and then do the classification within Monument itself.
In many imaging systems, this would be considered indexing (adding the index
information).


== Example Pyx Defined
*Version 2*

'''
*Filename:* my_fancy_img.png +
*Classification:* Human Resources +
*UIK:* 123456 +
*Import Date:* Apr 10, 2012 +
*Type:* Acceptance Letter +
*Employee Name:* David Thompson +
*Document Date:* Apr 1, 2012 +
*Comment:* Hand delivered for scanning +
David requested a copy of his letter be printed +
*Searchable Text:* --Redacted at the request of the employee--

*Version 1*

'''
*Filename:* my_fancy_img.png +
*Classification:* Human Resources +
*UIK:* 123456 +
*Import Date:* Apr 10, 2012 +
*Type:* Acceptance Letter +
*Employee Name:* David Thompsn +
*Document Date:* Apr 1, 2012 +
*Comment:* Hand delivered for scanning +
David requested a copy of his letter be printed +
*Searchable Text:* Dear David We are pleased to offer you the job as IT janitor and
are offering you the substantial salary of $12000 per year
