= Security
There are multiple layers of security within Monument. System level security, configuration security and document security.

== System Level Security
* Encryption of images
* Security of data store
* Web-service security
* Auditing
* Authentication
* Authorization

_Need to expand on system level security here_

== Configuration Security
There are many layers of security within monument. With a well defined security
layer, monument provides reliable, audited and secured storage of documents.
Monument provides image, data and system security that can be configured by
users. A robust permission system provides administrators and users the ability
to define view, insert, update and delete of images and data.

== Permissions
There are different permissions for different controls. There are controls
for who can add and delete users and groups and assign permissions to users
and groups.

There are controls defining who can setup definitions within the system.

Every pyx and relic have defined permissions, these permissions can be
inherited from their definitions.

The specific permissions are defined below.

=== System Permission Controls
==== User/Group
* Add, View, Update, Delete Users
* Add, View, Update, Delete Groups

==== Setup
Define new Pyx definitions (think of these as a template), add new relic
type definitions (think of these as a data element with validation rules),
define default retention policies for a Pyx definition, define versioning
control on Pyxes and relics, assign Pyx owners,  has full group controls and has
configuration controls that effect the system as a whole.

* Add, View, Update, Delete Pyx Definitions
* Add, Update, Delete Relic Definitions
* Add, View, Update, Delete Default Permissions on Pyx Definitions
* Add, View, Update, Delete Default Permissions on Relics Definitions


==== Pyx
* Add, View, Update, Delete, Version of an individual Pyx per group or user.

==== Relic
* Add, View, Update, Delete, Version of an individual Relic per group or user.

== Image Types
Monument can manipulate multiple image types. Because images are binary there is
always a possibility of security issues with any file uploaded. Monument
requires each image to be validated by the system where it undergoes evaluation
to make sure it is a valid type and contains no embedded code. Monument can also
resample and rewrite an image to eliminate security concerns. The types of
binary data that can be stored within Monument can be configured at the system
configuration level.

=== Raster Types
GIF, PNG, TIFF, BMP, JPG

=== Non-raster Types
SVG, PDF, DOCX, XLS


== Pyx Security
All relics within a pyx can have a varied set of permissions providing fine
grained control of what users can do. Permissions are always additive, except
when document fields are defined to be limited. These permissions are:

Insert:: User can create a new document, storing the file and its meta-data into the system.
View:: User can search document meta-data, comments and retrieve the document.
Update:: User can modify the document meta-data (if document defines that the data is modifiable)
Delete:: User can delete the document from the system. [Should we use a "Trash"?]
